/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  CalendarEvent,
  CalendarEvents,
  DayDescriptor,
} from './components/zijderoute-calendar/calendar.types';


export namespace Components {

  interface ZijderouteCalendarCell {
    'day': DayDescriptor;
    'events': CalendarEvent[];
    'selectedDay': DayDescriptor;
  }
  interface ZijderouteCalendarCellAttributes extends StencilHTMLAttributes {
    'day'?: DayDescriptor;
    'events'?: CalendarEvent[];
    'onEmitSelectDayEvent'?: (event: CustomEvent) => void;
    'selectedDay'?: DayDescriptor;
  }

  interface ZijderouteCalendarDetails {
    'events': CalendarEvent[];
    'selected': DayDescriptor;
  }
  interface ZijderouteCalendarDetailsAttributes extends StencilHTMLAttributes {
    'events'?: CalendarEvent[];
    'selected'?: DayDescriptor;
  }

  interface ZijderouteCalendarGrid {
    'date': Date;
    'events': CalendarEvents;
    'selected': DayDescriptor;
  }
  interface ZijderouteCalendarGridAttributes extends StencilHTMLAttributes {
    'date'?: Date;
    'events'?: CalendarEvents;
    'selected'?: DayDescriptor;
  }

  interface ZijderouteCalendar {
    'calendarId': string;
    'serviceAccountEmail': string;
    'tokenSignUrl': string;
  }
  interface ZijderouteCalendarAttributes extends StencilHTMLAttributes {
    'calendarId'?: string;
    'serviceAccountEmail'?: string;
    'tokenSignUrl'?: string;
  }

  interface ZijderouteArrowLeft {
    'fillColor': string;
  }
  interface ZijderouteArrowLeftAttributes extends StencilHTMLAttributes {
    'fillColor'?: string;
  }

  interface ZijderouteArrowRight {
    'fillColor': string;
  }
  interface ZijderouteArrowRightAttributes extends StencilHTMLAttributes {
    'fillColor'?: string;
  }

  interface ZijderouteCalendarIcon {
    'backgroundColor': string;
    'fillColor': string;
  }
  interface ZijderouteCalendarIconAttributes extends StencilHTMLAttributes {
    'backgroundColor'?: string;
    'fillColor'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ZijderouteCalendarCell': Components.ZijderouteCalendarCell;
    'ZijderouteCalendarDetails': Components.ZijderouteCalendarDetails;
    'ZijderouteCalendarGrid': Components.ZijderouteCalendarGrid;
    'ZijderouteCalendar': Components.ZijderouteCalendar;
    'ZijderouteArrowLeft': Components.ZijderouteArrowLeft;
    'ZijderouteArrowRight': Components.ZijderouteArrowRight;
    'ZijderouteCalendarIcon': Components.ZijderouteCalendarIcon;
  }

  interface StencilIntrinsicElements {
    'zijderoute-calendar-cell': Components.ZijderouteCalendarCellAttributes;
    'zijderoute-calendar-details': Components.ZijderouteCalendarDetailsAttributes;
    'zijderoute-calendar-grid': Components.ZijderouteCalendarGridAttributes;
    'zijderoute-calendar': Components.ZijderouteCalendarAttributes;
    'zijderoute-arrow-left': Components.ZijderouteArrowLeftAttributes;
    'zijderoute-arrow-right': Components.ZijderouteArrowRightAttributes;
    'zijderoute-calendar-icon': Components.ZijderouteCalendarIconAttributes;
  }


  interface HTMLZijderouteCalendarCellElement extends Components.ZijderouteCalendarCell, HTMLStencilElement {}
  var HTMLZijderouteCalendarCellElement: {
    prototype: HTMLZijderouteCalendarCellElement;
    new (): HTMLZijderouteCalendarCellElement;
  };

  interface HTMLZijderouteCalendarDetailsElement extends Components.ZijderouteCalendarDetails, HTMLStencilElement {}
  var HTMLZijderouteCalendarDetailsElement: {
    prototype: HTMLZijderouteCalendarDetailsElement;
    new (): HTMLZijderouteCalendarDetailsElement;
  };

  interface HTMLZijderouteCalendarGridElement extends Components.ZijderouteCalendarGrid, HTMLStencilElement {}
  var HTMLZijderouteCalendarGridElement: {
    prototype: HTMLZijderouteCalendarGridElement;
    new (): HTMLZijderouteCalendarGridElement;
  };

  interface HTMLZijderouteCalendarElement extends Components.ZijderouteCalendar, HTMLStencilElement {}
  var HTMLZijderouteCalendarElement: {
    prototype: HTMLZijderouteCalendarElement;
    new (): HTMLZijderouteCalendarElement;
  };

  interface HTMLZijderouteArrowLeftElement extends Components.ZijderouteArrowLeft, HTMLStencilElement {}
  var HTMLZijderouteArrowLeftElement: {
    prototype: HTMLZijderouteArrowLeftElement;
    new (): HTMLZijderouteArrowLeftElement;
  };

  interface HTMLZijderouteArrowRightElement extends Components.ZijderouteArrowRight, HTMLStencilElement {}
  var HTMLZijderouteArrowRightElement: {
    prototype: HTMLZijderouteArrowRightElement;
    new (): HTMLZijderouteArrowRightElement;
  };

  interface HTMLZijderouteCalendarIconElement extends Components.ZijderouteCalendarIcon, HTMLStencilElement {}
  var HTMLZijderouteCalendarIconElement: {
    prototype: HTMLZijderouteCalendarIconElement;
    new (): HTMLZijderouteCalendarIconElement;
  };

  interface HTMLElementTagNameMap {
    'zijderoute-calendar-cell': HTMLZijderouteCalendarCellElement
    'zijderoute-calendar-details': HTMLZijderouteCalendarDetailsElement
    'zijderoute-calendar-grid': HTMLZijderouteCalendarGridElement
    'zijderoute-calendar': HTMLZijderouteCalendarElement
    'zijderoute-arrow-left': HTMLZijderouteArrowLeftElement
    'zijderoute-arrow-right': HTMLZijderouteArrowRightElement
    'zijderoute-calendar-icon': HTMLZijderouteCalendarIconElement
  }

  interface ElementTagNameMap {
    'zijderoute-calendar-cell': HTMLZijderouteCalendarCellElement;
    'zijderoute-calendar-details': HTMLZijderouteCalendarDetailsElement;
    'zijderoute-calendar-grid': HTMLZijderouteCalendarGridElement;
    'zijderoute-calendar': HTMLZijderouteCalendarElement;
    'zijderoute-arrow-left': HTMLZijderouteArrowLeftElement;
    'zijderoute-arrow-right': HTMLZijderouteArrowRightElement;
    'zijderoute-calendar-icon': HTMLZijderouteCalendarIconElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
